sonar.projectKey=PSA-Analise-Text-To-SQL_text-to-sql
sonar.organization=psa-analise-text-to-sql
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/venv/**, **/.venv/**, **/env/**, **/.tox/**, **/dist/**, **/build/**
sonar.cpd.exclusions=**/migrations/**

sonar.javascript.lcov.reportPaths=
sonar.python.coverage.reportPaths=

sonar.python.version=3.12
sonar.language=py

sonar.scm.disabled=false
